package tofuya:provider-gitlab;

interface gitlab-terraform-api {
    record connection-config {
        api-url: string,
        auth-token: option<string>,
    }

    get-state-names: func(config: connection-config, project-path: string) -> result<list<string>, string>;
}

world gitlab-provider {
    export gitlab-terraform-api;
}
