on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Required to create GH releases
      contents: write
      # Required to push to GHCR
      packages: write
      # Required by cosign keyless signing
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip1, wasm32-wasip2
      - name: Build the Wasm Component
        run: cargo component build --release
      - name: Login to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Version without 'v' prefix
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
      - name: Publish WASM
        uses: ./.github/actions/wit
        with:
          file: 'target/wasm32-wasip1/release/tofuya_provider_gitlab.wasm'
          oci-description: 'Gitlab library for tofuya plugins'
          oci-reference-without-tag: 'ghcr.io/tmuntaner/tofuya-provider-gitlab'
          version: ${{ steps.version.outputs.VERSION }}
